"""Clinical content libraries for the synthetic trial corpus.

Pure data. No generation logic — see generate_trial_corpus.py.

Vocabularies marked OBSERVED are taken from the Trial IntelX sample output.
Vocabularies marked INFERRED are plausible reconstructions: the Data Dictionary
summary exhibit names the controlled vocabulary (Appendices A-I) but does not
reproduce its permitted values. Swap these when the full Data Dictionary lands.
"""

# --- Appendix A: Phase (OBSERVED partial, extended) ---
PHASES = ["1", "1/2", "2", "2/3", "3", "4"]

# --- Appendix B: Study Type (OBSERVED) ---
STUDY_TYPES = [
    "Interventional (Experimental), Prospective",
    "Interventional (Experimental), Prospective, Open-Label Extension",
    "Observational, Prospective",
]

# --- Appendix C: Study Design (OBSERVED partial, extended) ---
DESIGN_ELEMENTS = [
    "Randomized Controlled Trial (RCT)",
    "Double-Blind",
    "Single-Blind",
    "Open-Label",
    "Cross-Over Design",
    "Parallel Group",
    "Dose-Escalation",
    "Adaptive Design",
    "Basket Design",
    "Umbrella Design",
]

# --- Appendix D: Randomization Scheme (OBSERVED) ---
RANDOMIZATION_SCHEMES = [
    "Simple (X:Y)",
    "Simple (X:Y), Stratified",
    "Block",
    "Block, Stratified",
    "Not Applicable",
]

# --- Appendix E: Dosing Frequency (OBSERVED partial, extended) ---
DOSING_FREQUENCIES = [
    "Once", "QD: Once daily", "BID: Twice daily", "TID: Three times daily",
    "QW: Once weekly", "Q2W: Once every two weeks", "Q3W: Once every three weeks",
    "Q4W: Once every four weeks", "QM: Once monthly", "PRN: As needed",
]

# --- Appendix F: Route of Administration (OBSERVED partial, extended) ---
ROUTES = [
    "Oral", "Intravenous", "Subcutaneous", "Intramuscular",
    "Inhalation (Pulmonary)", "Intranasal", "Topical", "Ophthalmic", "Intrathecal",
]

# --- Appendix G: Objective & Endpoint Domain (OBSERVED) ---
DOMAINS = [
    "Effectiveness", "Comparative Effectiveness", "Safety", "Tolerability",
    "Pharmacokinetics", "Pharmacodynamics", "Immunogenicity", "QoL", "Health Economics",
]

# --- Appendix H: Eligibility Categorization (OBSERVED, all 15 values) ---
ELIGIBILITY_CATEGORIES = [
    "Age", "Sex", "Diagnosis", "Medical History", "Comorbidities",
    "Procedural Values", "Lab Values", "Concomitant Medications",
    "Pregnancy/Breastfeeding/Contraception", "Ability to Consent/Comply",
    "Allergies/Reactions", "Substance Abuse",
    "Prior/Concurrent participation in a trial",
    "Prior/Concurrent treatment (e.g. line of therapy)", "Other",
]

# --- Appendix I: Amendment Type (INFERRED) ---
AMENDMENT_TYPES = [
    "Eligibility Criteria Change", "Endpoint Change",
    "Schedule of Assessments Change", "Dosing Change", "Sample Size Change",
    "Safety Update", "Statistical Analysis Change", "Study Design Change",
    "Administrative",
]

INVASIVENESS = [
    "Procedure (Non - Invasive)", "Procedure (Minimally Invasive)",
    "Procedure (Moderately Invasive)", "Procedure (Highly Invasive)",
]

# --------------------------------------------------------------------------
# Therapeutic areas. `weight` sets corpus share; `deep` areas get more protocols.
# --------------------------------------------------------------------------

THERAPEUTIC_AREAS = {
    "Respiratory": {
        "deep": True,
        "disease_areas": {
            "Asthma": ["Severe Eosinophilic Asthma", "Moderate-to-Severe Asthma", "Acute Asthma"],
            "COPD": ["Moderate-to-Severe COPD", "COPD with Chronic Bronchitis"],
            "Interstitial Lung Disease": ["Idiopathic Pulmonary Fibrosis", "Progressive Pulmonary Fibrosis"],
            "Cystic Fibrosis": ["Cystic Fibrosis (F508del)"],
        },
        "routes": ["Inhalation (Pulmonary)", "Subcutaneous", "Oral"],
        "objectives": [
            ("Assess and compare efficacy of IPs on lung function between treatment arms", "Comparative Effectiveness"),
            ("Evaluate the effect of IP on exacerbation frequency", "Effectiveness"),
            ("Characterize the safety and tolerability of IP", "Safety"),
            ("Evaluate the effect of IP on patient-reported respiratory symptoms", "QoL"),
        ],
        "endpoints": [
            ("Change from baseline in pre-bronchodilator forced expiratory volume in 1 second (FEV1)", "Effectiveness"),
            ("Change from baseline in post-bronchodilator forced expiratory volume in 1 second (FEV1)", "Effectiveness"),
            ("Annualized rate of moderate or severe exacerbations", "Effectiveness"),
            ("Change from baseline in forced vital capacity (FVC)", "Effectiveness"),
            ("Change from baseline in Asthma Control Questionnaire (ACQ-7) score", "QoL"),
            ("Change from baseline in St George's Respiratory Questionnaire (SGRQ) total score", "QoL"),
            ("Change from baseline in diffusing capacity of the lungs for carbon monoxide (DLCO)", "Effectiveness"),
            ("Change from baseline in 6-minute walk distance (6MWD)", "Effectiveness"),
            ("Count of treatment emergent adverse events", "Safety"),
            ("Count of treatment emergent serious adverse events", "Safety"),
            ("Change from baseline in fractional exhaled nitric oxide (FeNO)", "Pharmacodynamics"),
            ("Serum concentration of IP over time", "Pharmacokinetics"),
            ("Incidence of anti-drug antibodies", "Immunogenicity"),
        ],
        "procedures": [
            ("Spirometry", "Procedure (Non - Invasive)", 25, "20150-9"),
            ("Body plethysmography", "Procedure (Non - Invasive)", 30, "19868-9"),
            ("Fractional exhaled nitric oxide (FeNO)", "Procedure (Non - Invasive)", 10, "70241-5"),
            ("Reversibility testing", "Procedure (Non - Invasive)", 45, "19926-5"),
            ("Sputum induction", "Procedure (Minimally Invasive)", 40, "33243-3"),
            ("High-resolution computed tomography (HRCT) chest", "Procedure (Non - Invasive)", 30, "30745-4"),
            ("Bronchoscopy with bronchoalveolar lavage", "Procedure (Highly Invasive)", 90, "17909-3"),
            ("6-minute walk test", "Procedure (Non - Invasive)", 20, "64098-7"),
            ("Pulse oximetry", "Procedure (Non - Invasive)", 5, "59408-5"),
        ],
        "prohibited": [
            "Systemic corticosteroids", "Long-acting beta-2 agonists (LABAs)",
            "Long-acting muscarinic antagonists (LAMAs)", "Leukotriene modifiers",
            "Omalizumab", "Other anti-IL5 or anti-IL5R biologics", "Xanthine derivatives",
            "Cromolyns", "Non-selective beta-blocking agents", "Other investigational drugs",
            "Live attenuated vaccines", "Immunosuppressive therapy",
        ],
    },
    "Oncology": {
        "deep": True,
        "disease_areas": {
            "Thoracic Oncology": ["Advanced Non-Small Cell Lung Cancer", "Extensive-Stage Small Cell Lung Cancer"],
            "Breast Oncology": ["HR+/HER2- Metastatic Breast Cancer", "Triple-Negative Breast Cancer"],
            "Gastrointestinal Oncology": ["Metastatic Colorectal Cancer", "Advanced Gastric Adenocarcinoma"],
            "Hematologic Malignancy": ["Relapsed/Refractory Multiple Myeloma", "Acute Myeloid Leukemia"],
        },
        "routes": ["Intravenous", "Oral", "Subcutaneous"],
        "objectives": [
            ("Evaluate the antitumor activity of IP as measured by objective response rate", "Effectiveness"),
            ("Assess and compare progression-free survival between treatment arms", "Comparative Effectiveness"),
            ("Evaluate overall survival in the intent-to-treat population", "Effectiveness"),
            ("Characterize the safety and tolerability profile of IP", "Safety"),
            ("Characterize the pharmacokinetic profile of IP", "Pharmacokinetics"),
        ],
        "endpoints": [
            ("Objective response rate (ORR) per RECIST v1.1", "Effectiveness"),
            ("Progression-free survival (PFS) per RECIST v1.1", "Effectiveness"),
            ("Overall survival (OS)", "Effectiveness"),
            ("Duration of response (DoR)", "Effectiveness"),
            ("Disease control rate (DCR)", "Effectiveness"),
            ("Time to response (TTR)", "Effectiveness"),
            ("Minimal residual disease (MRD) negativity rate", "Effectiveness"),
            ("Count of dose-limiting toxicities (DLTs)", "Safety"),
            ("Count of treatment emergent adverse events by CTCAE v5.0 grade", "Safety"),
            ("Count of dose reductions and dose interruptions", "Tolerability"),
            ("Maximum observed plasma concentration (Cmax)", "Pharmacokinetics"),
            ("Area under the plasma concentration-time curve (AUC)", "Pharmacokinetics"),
            ("Change from baseline in EORTC QLQ-C30 global health status", "QoL"),
        ],
        "procedures": [
            ("Computed tomography (CT) with contrast", "Procedure (Minimally Invasive)", 45, "24627-2"),
            ("Magnetic resonance imaging (MRI)", "Procedure (Non - Invasive)", 60, "24590-2"),
            ("Tumor biopsy", "Procedure (Highly Invasive)", 90, "33746-5"),
            ("Bone marrow aspirate and biopsy", "Procedure (Highly Invasive)", 60, "33717-6"),
            ("Echocardiogram (ECHO)", "Procedure (Non - Invasive)", 40, "34552-0"),
            ("Multigated acquisition (MUGA) scan", "Procedure (Minimally Invasive)", 45, "39024-3"),
            ("Pharmacokinetic blood sampling", "Procedure (Minimally Invasive)", 15, "33747-3"),
            ("Hematology panel", "Procedure (Minimally Invasive)", 10, "58410-2"),
            ("Serum chemistry panel", "Procedure (Minimally Invasive)", 10, "24323-8"),
            ("ECOG performance status assessment", "Procedure (Non - Invasive)", 5, "89247-1"),
            ("Positron emission tomography (PET) scan", "Procedure (Minimally Invasive)", 75, "44136-0"),
        ],
        "prohibited": [
            "Other antineoplastic therapy", "Live attenuated vaccines",
            "Strong CYP3A4 inhibitors", "Strong CYP3A4 inducers",
            "Systemic immunosuppressants", "Chronic systemic corticosteroids >10 mg/day prednisone equivalent",
            "Herbal supplements with known antineoplastic activity", "Other investigational drugs",
            "Therapeutic anticoagulation (except prophylactic)", "Growth factors within 14 days of dosing",
        ],
    },
    "Immunology & Inflammation": {
        "deep": False,
        "disease_areas": {
            "Rheumatology": ["Moderate-to-Severe Rheumatoid Arthritis", "Active Psoriatic Arthritis", "Systemic Lupus Erythematosus"],
            "Dermatology": ["Moderate-to-Severe Plaque Psoriasis", "Moderate-to-Severe Atopic Dermatitis"],
            "Gastroenterology": ["Moderately-to-Severely Active Ulcerative Colitis", "Moderately-to-Severely Active Crohn's Disease"],
        },
        "routes": ["Subcutaneous", "Oral", "Intravenous"],
        "objectives": [
            ("Assess and compare clinical response between treatment arms", "Comparative Effectiveness"),
            ("Evaluate the efficacy of IP in inducing clinical remission", "Effectiveness"),
            ("Characterize the long-term safety profile of IP", "Safety"),
            ("Evaluate the effect of IP on health-related quality of life", "QoL"),
        ],
        "endpoints": [
            ("Proportion of participants achieving ACR20 response", "Effectiveness"),
            ("Proportion of participants achieving ACR50 response", "Effectiveness"),
            ("Proportion of participants achieving PASI 75 response", "Effectiveness"),
            ("Proportion of participants achieving PASI 90 response", "Effectiveness"),
            ("Change from baseline in Disease Activity Score-28 (DAS28-CRP)", "Effectiveness"),
            ("Proportion of participants achieving clinical remission by modified Mayo score", "Effectiveness"),
            ("Change from baseline in Eczema Area and Severity Index (EASI)", "Effectiveness"),
            ("Proportion of participants achieving endoscopic improvement", "Effectiveness"),
            ("Change from baseline in SLE Disease Activity Index (SLEDAI-2K)", "Effectiveness"),
            ("Count of treatment emergent adverse events", "Safety"),
            ("Incidence of serious infections", "Safety"),
            ("Incidence of anti-drug antibodies", "Immunogenicity"),
            ("Change from baseline in Health Assessment Questionnaire (HAQ-DI)", "QoL"),
        ],
        "procedures": [
            ("Tender and swollen joint count (68/66)", "Procedure (Non - Invasive)", 20, "72514-3"),
            ("Psoriasis Area and Severity Index (PASI) scoring", "Procedure (Non - Invasive)", 15, "89534-2"),
            ("Ileocolonoscopy with central reading", "Procedure (Highly Invasive)", 120, "18746-8"),
            ("Skin punch biopsy", "Procedure (Moderately Invasive)", 30, "33723-4"),
            ("QuantiFERON-TB Gold test", "Procedure (Minimally Invasive)", 10, "88516-2"),
            ("High-sensitivity C-reactive protein (hsCRP)", "Procedure (Minimally Invasive)", 10, "30522-7"),
            ("Erythrocyte sedimentation rate (ESR)", "Procedure (Minimally Invasive)", 10, "30341-2"),
            ("Chest radiograph", "Procedure (Non - Invasive)", 15, "36643-5"),
            ("Fecal calprotectin", "Procedure (Non - Invasive)", 10, "38445-3"),
        ],
        "prohibited": [
            "Other biologic disease-modifying antirheumatic drugs (bDMARDs)",
            "Janus kinase (JAK) inhibitors", "Cyclophosphamide", "Live attenuated vaccines",
            "Systemic corticosteroids above protocol-defined threshold", "Phototherapy",
            "Topical corticosteroids of class I-II potency", "Rituximab or other B-cell depleting agents",
            "Other investigational drugs", "Tumour necrosis factor alpha inhibitors",
        ],
    },
    "Cardiometabolic": {
        "deep": False,
        "disease_areas": {
            "Heart Failure": ["Heart Failure with Reduced Ejection Fraction", "Heart Failure with Preserved Ejection Fraction"],
            "Diabetes": ["Type 2 Diabetes Mellitus", "Type 1 Diabetes Mellitus"],
            "Obesity": ["Obesity with Weight-Related Comorbidity"],
            "Dyslipidemia": ["Heterozygous Familial Hypercholesterolemia"],
        },
        "routes": ["Oral", "Subcutaneous", "Intravenous"],
        "objectives": [
            ("Assess and compare glycemic control between treatment arms", "Comparative Effectiveness"),
            ("Evaluate the effect of IP on body weight", "Effectiveness"),
            ("Evaluate the effect of IP on cardiovascular outcomes", "Effectiveness"),
            ("Characterize the safety and tolerability of IP", "Safety"),
        ],
        "endpoints": [
            ("Change from baseline in glycated hemoglobin (HbA1c)", "Effectiveness"),
            ("Percent change from baseline in body weight", "Effectiveness"),
            ("Change from baseline in low-density lipoprotein cholesterol (LDL-C)", "Effectiveness"),
            ("Time to first occurrence of major adverse cardiovascular event (MACE)", "Effectiveness"),
            ("Change from baseline in N-terminal pro b-type natriuretic peptide (NT-proBNP)", "Effectiveness"),
            ("Change from baseline in Kansas City Cardiomyopathy Questionnaire (KCCQ) score", "QoL"),
            ("Proportion of participants achieving HbA1c < 7.0%", "Effectiveness"),
            ("Change from baseline in left ventricular ejection fraction (LVEF)", "Effectiveness"),
            ("Incidence of documented hypoglycemia", "Safety"),
            ("Count of treatment emergent adverse events", "Safety"),
            ("Change from baseline in estimated glomerular filtration rate (eGFR)", "Safety"),
        ],
        "procedures": [
            ("Glycated hemoglobin (HbA1c)", "Procedure (Minimally Invasive)", 10, "4548-4"),
            ("Fasting plasma glucose", "Procedure (Minimally Invasive)", 10, "1558-6"),
            ("Oral glucose tolerance test (OGTT)", "Procedure (Minimally Invasive)", 150, "14995-4"),
            ("Continuous glucose monitoring (CGM) placement", "Procedure (Minimally Invasive)", 25, "99504-3"),
            ("Echocardiogram (ECHO)", "Procedure (Non - Invasive)", 40, "34552-0"),
            ("Dual-energy X-ray absorptiometry (DXA)", "Procedure (Non - Invasive)", 30, "38261-4"),
            ("Lipid panel", "Procedure (Minimally Invasive)", 10, "57698-3"),
            ("12-lead electrocardiogram (ECG)", "Procedure (Non - Invasive)", 15, "11524-6"),
            ("Ambulatory blood pressure monitoring", "Procedure (Non - Invasive)", 20, "76632-8"),
        ],
        "prohibited": [
            "Other glucose-lowering agents outside protocol-permitted background therapy",
            "Systemic corticosteroids", "Weight-loss medications", "Bariatric surgery during study",
            "Other GLP-1 receptor agonists", "Strong CYP3A4 inhibitors",
            "Other investigational drugs", "Loop diuretics above protocol-defined dose",
        ],
    },
    "Neurology": {
        "deep": False,
        "disease_areas": {
            "Neurodegeneration": ["Early Symptomatic Alzheimer's Disease", "Early Parkinson's Disease", "Amyotrophic Lateral Sclerosis"],
            "Neuroinflammation": ["Relapsing-Remitting Multiple Sclerosis"],
            "Epilepsy": ["Drug-Resistant Focal Onset Seizures"],
        },
        "routes": ["Oral", "Intravenous", "Subcutaneous", "Intrathecal"],
        "objectives": [
            ("Evaluate the effect of IP on disease progression", "Effectiveness"),
            ("Assess and compare cognitive decline between treatment arms", "Comparative Effectiveness"),
            ("Characterize the safety and tolerability of IP", "Safety"),
            ("Evaluate the effect of IP on biomarkers of disease", "Pharmacodynamics"),
        ],
        "endpoints": [
            ("Change from baseline in Clinical Dementia Rating-Sum of Boxes (CDR-SB)", "Effectiveness"),
            ("Change from baseline in Alzheimer's Disease Assessment Scale-Cognitive Subscale (ADAS-Cog)", "Effectiveness"),
            ("Annualized relapse rate (ARR)", "Effectiveness"),
            ("Change from baseline in Expanded Disability Status Scale (EDSS)", "Effectiveness"),
            ("Change from baseline in Movement Disorder Society-Unified Parkinson's Disease Rating Scale (MDS-UPDRS)", "Effectiveness"),
            ("Change from baseline in ALS Functional Rating Scale-Revised (ALSFRS-R)", "Effectiveness"),
            ("Percent change from baseline in seizure frequency", "Effectiveness"),
            ("Change from baseline in amyloid PET standardized uptake value ratio (SUVR)", "Pharmacodynamics"),
            ("Change from baseline in plasma neurofilament light chain (NfL)", "Pharmacodynamics"),
            ("Count of new or enlarging T2 lesions on MRI", "Effectiveness"),
            ("Incidence of amyloid-related imaging abnormalities (ARIA)", "Safety"),
            ("Count of treatment emergent adverse events", "Safety"),
        ],
        "procedures": [
            ("Brain magnetic resonance imaging (MRI)", "Procedure (Non - Invasive)", 60, "24590-2"),
            ("Amyloid positron emission tomography (PET)", "Procedure (Minimally Invasive)", 90, "44136-0"),
            ("Lumbar puncture for cerebrospinal fluid collection", "Procedure (Highly Invasive)", 60, "33746-5"),
            ("Cognitive assessment battery", "Procedure (Non - Invasive)", 90, "72133-2"),
            ("Mini-Mental State Examination (MMSE)", "Procedure (Non - Invasive)", 15, "72106-8"),
            ("Electroencephalogram (EEG)", "Procedure (Non - Invasive)", 45, "24708-0"),
            ("Neurological examination", "Procedure (Non - Invasive)", 30, "11450-4"),
            ("Columbia-Suicide Severity Rating Scale (C-SSRS)", "Procedure (Non - Invasive)", 15, "93373-9"),
            ("Plasma biomarker sampling", "Procedure (Minimally Invasive)", 15, "33747-3"),
        ],
        "prohibited": [
            "Other disease-modifying therapies", "Anti-amyloid monoclonal antibodies",
            "Chronic anticoagulation", "Strong CYP3A4 inhibitors", "Typical antipsychotics",
            "Other investigational drugs", "Immunosuppressive therapy",
            "Medications with significant anticholinergic burden",
        ],
    },
}

# --------------------------------------------------------------------------
# Eligibility criterion templates.
#
# `restrictiveness` (0-1) is the generative model's dial: it feeds the protocol
# restrictiveness index, which in turn drives screen-fail rate. `diversity_drag`
# (0-1) marks criteria known to disproportionately exclude non-White, older, and
# lower-income populations -- BMI caps, renal/hepatic gates, comorbidity bars.
# --------------------------------------------------------------------------

UNIVERSAL_INCLUSION = [
    dict(label="Age", cat="Age", rel=">=", low="18", low_unit="years",
         rel2="<=", high="{max_age}", high_unit="years", restrictiveness=0.10, diversity_drag=0.15),
    dict(label="Sex", cat="Sex", rel=" =", low="male or female", restrictiveness=0.0, diversity_drag=0.0),
    dict(label="Written informed consent", cat="Ability to Consent/Comply", rel=" =", low="Yes",
         restrictiveness=0.05, diversity_drag=0.05),
    dict(label="Ability to comply with the study schedule and procedures", cat="Ability to Consent/Comply",
         rel=" =", low="Yes", restrictiveness=0.25, diversity_drag=0.45,
         notes="Based on Investigator's judgement"),
    dict(label="Body Mass Index (BMI)", cat="Procedural Values", rel=">=", low="18", low_unit="kg/m²",
         rel2="<=", high="{bmi_cap}", high_unit="kg/m²", restrictiveness=0.35, diversity_drag=0.70),
    dict(label="Highly effective contraception", cat="Pregnancy/Breastfeeding/Contraception",
         rel=" =", low="Yes", tp_rel="<=", tp_val="{contraception_window}", tp_unit="days",
         tp_desc="after", tp_start="last dose of study drug",
         restrictiveness=0.15, diversity_drag=0.10, notes="For female participants of childbearing potential"),
]

UNIVERSAL_EXCLUSION = [
    dict(label="Pregnancy test", cat="Pregnancy/Breastfeeding/Contraception", rel=" =", low="Negative",
         tp_desc="at", tp_start="screening", restrictiveness=0.05, diversity_drag=0.0),
    dict(label="Breastfeeding", cat="Pregnancy/Breastfeeding/Contraception", rel=" =", low="No",
         restrictiveness=0.05, diversity_drag=0.0),
    dict(label="Clinically significant renal disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.45, diversity_drag=0.75),
    dict(label="Clinically significant hepatic disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.40, diversity_drag=0.60),
    dict(label="Clinically significant cardiovascular disease", cat="Comorbidities", rel=" =", low="No",
         tp_rel="<=", tp_val="6", tp_unit="months", tp_desc="before", tp_start="screening",
         restrictiveness=0.50, diversity_drag=0.70),
    dict(label="Clinically significant endocrine disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.35, diversity_drag=0.55,
         notes="Includes uncontrolled diabetes mellitus, uncontrolled thyroid disorder"),
    dict(label="Clinically significant gastrointestinal disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.30, diversity_drag=0.30),
    dict(label="Estimated glomerular filtration rate (eGFR)", cat="Lab Values", rel=">=",
         low="{egfr_floor}", low_unit="mL/min/1.73m²", restrictiveness=0.55, diversity_drag=0.80),
    dict(label="Alanine aminotransferase (ALT)", cat="Lab Values", rel="<=", low="{alt_ceiling}",
         low_unit="x ULN", restrictiveness=0.35, diversity_drag=0.45),
    dict(label="Total bilirubin", cat="Lab Values", rel="<=", low="1.5", low_unit="x ULN",
         restrictiveness=0.30, diversity_drag=0.50),
    dict(label="Absolute neutrophil count (ANC)", cat="Lab Values", rel=">=", low="1.5",
         low_unit="x 10⁹/L", restrictiveness=0.40, diversity_drag=0.65,
         notes="Benign ethnic neutropenia not accounted for"),
    dict(label="Hemoglobin", cat="Lab Values", rel=">=", low="{hgb_floor}", low_unit="g/dL",
         restrictiveness=0.35, diversity_drag=0.60),
    dict(label="QTcF interval (Fridericia's correction)", cat="Procedural Values", rel="<=",
         low="{qtc_ceiling}", low_unit="msec", restrictiveness=0.30, diversity_drag=0.35),
    dict(label="Known hypersensitivity to the investigational product or excipients",
         cat="Allergies/Reactions", rel=" =", low="No", restrictiveness=0.10, diversity_drag=0.0),
    dict(label="History of malignancy", cat="Medical History", rel=" =", low="No",
         tp_rel="<=", tp_val="5", tp_unit="years", tp_desc="before", tp_start="screening",
         restrictiveness=0.35, diversity_drag=0.30,
         notes="Excluding adequately treated non-melanoma skin cancer or in-situ cervical carcinoma"),
    dict(label="Human immunodeficiency virus (HIV) test", cat="Medical History", rel=" =", low="Negative",
         restrictiveness=0.25, diversity_drag=0.75),
    dict(label="Hepatitis B surface antigen", cat="Medical History", rel=" =", low="Negative",
         restrictiveness=0.25, diversity_drag=0.70),
    dict(label="Hepatitis C antibody", cat="Medical History", rel=" =", low="Negative",
         restrictiveness=0.25, diversity_drag=0.65),
    dict(label="Active or latent tuberculosis", cat="Medical History", rel=" =", low="No",
         restrictiveness=0.30, diversity_drag=0.70),
    dict(label="Substance abuse", cat="Substance Abuse", rel=" =", low="No",
         tp_rel="<=", tp_val="{substance_window}", tp_unit="years", tp_desc="before", tp_start="screening",
         restrictiveness=0.35, diversity_drag=0.55),
    dict(label="Current tobacco or nicotine use", cat="Substance Abuse", rel=" =", low="No",
         restrictiveness=0.40, diversity_drag=0.50),
    dict(label="Participation in another interventional clinical trial",
         cat="Prior/Concurrent participation in a trial", rel=" =", low="No",
         tp_rel="<=", tp_val="{washout_days}", tp_unit="days", tp_desc="before", tp_start="screening",
         restrictiveness=0.30, diversity_drag=0.20, notes="or 5 half-lives, whichever is longer"),
    dict(label="Receipt of prohibited concomitant medication", cat="Concomitant Medications",
         rel=" =", low="No", tp_rel="<=", tp_val="{washout_days}", tp_unit="days",
         tp_desc="before", tp_start="baseline", restrictiveness=0.45, diversity_drag=0.40,
         notes="Patients should discontinue prohibited medications before treatment period"),
    dict(label="Major surgery", cat="Medical History", rel=" =", low="No", tp_rel="<=", tp_val="12",
         tp_unit="weeks", tp_desc="before", tp_start="screening", restrictiveness=0.20, diversity_drag=0.25),
    dict(label="Any condition that in the opinion of the Investigator would compromise participant safety",
         cat="Other", rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.40,
         notes="Investigator discretion criterion"),
]

# TA-specific criteria. Keyed by therapeutic area.
TA_CRITERIA = {
    "Respiratory": {
        "inclusion": [
            dict(label="Forced Expiratory Volume in 1 second (FEV1)", cat="Diagnosis", rel=">=",
                 low="{fev1_floor}", low_unit="% of predicted normal value",
                 tp_desc="at", tp_start="screening", restrictiveness=0.55, diversity_drag=0.40),
            dict(label="Reversible bronchoconstriction (increase in FEV1)", cat="Procedural Values",
                 rel=">=", low="12", low_unit="%", tp_rel="<=", tp_val="30", tp_unit="minutes",
                 tp_desc="after", tp_start="bronchodilator administration",
                 restrictiveness=0.50, diversity_drag=0.30),
            dict(label="Documented physician-diagnosed asthma", cat="Diagnosis", rel=" =", low="Yes",
                 tp_rel=">=", tp_val="12", tp_unit="months", tp_desc="before", tp_start="screening",
                 restrictiveness=0.25, diversity_drag=0.45),
            dict(label="Blood eosinophil count", cat="Lab Values", rel=">=", low="{eos_floor}",
                 low_unit="cells/µL", tp_desc="at", tp_start="screening",
                 restrictiveness=0.60, diversity_drag=0.35),
            dict(label="History of exacerbations requiring systemic corticosteroids", cat="Medical History",
                 rel=">=", low="2", low_unit="events", tp_rel="<=", tp_val="12", tp_unit="months",
                 tp_desc="before", tp_start="screening", restrictiveness=0.50, diversity_drag=0.30),
            dict(label="Asthma Control Questionnaire (ACQ-7) score", cat="Procedural Values", rel=">=",
                 low="1.5", tp_desc="at", tp_start="screening", restrictiveness=0.35, diversity_drag=0.25),
            dict(label="Stable maintenance therapy with medium-to-high dose inhaled corticosteroids",
                 cat="Concomitant Medications", rel=" =", low="Yes", tp_rel=">=", tp_val="3",
                 tp_unit="months", tp_desc="before", tp_start="screening",
                 restrictiveness=0.45, diversity_drag=0.55),
        ],
        "exclusion": [
            dict(label="Smoking history", cat="Substance Abuse", rel="<=", low="10", low_unit="pack-years",
                 restrictiveness=0.45, diversity_drag=0.55),
            dict(label="Asthma exacerbation requiring hospitalization", cat="Medical History", rel=" =",
                 low="No", tp_rel="<=", tp_val="{exac_window}", tp_unit="weeks", tp_desc="before",
                 tp_start="screening", restrictiveness=0.40, diversity_drag=0.60),
            dict(label="Lower respiratory tract infection", cat="Medical History", rel=" =", low="No",
                 tp_rel="<=", tp_val="4", tp_unit="weeks", tp_desc="before", tp_start="screening",
                 restrictiveness=0.25, diversity_drag=0.30),
            dict(label="Other clinically significant pulmonary disease", cat="Comorbidities", rel=" =",
                 low="No", restrictiveness=0.35, diversity_drag=0.45),
            dict(label="Chronic oral corticosteroid use", cat="Concomitant Medications", rel=" =", low="No",
                 restrictiveness=0.35, diversity_drag=0.40),
        ],
    },
    "Oncology": {
        "inclusion": [
            dict(label="Histologically or cytologically confirmed diagnosis", cat="Diagnosis", rel=" =",
                 low="Yes", restrictiveness=0.30, diversity_drag=0.40),
            dict(label="Eastern Cooperative Oncology Group (ECOG) performance status",
                 cat="Procedural Values", rel="<=", low="{ecog_max}", tp_desc="at", tp_start="screening",
                 restrictiveness=0.60, diversity_drag=0.70),
            dict(label="Measurable disease per RECIST v1.1", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.40, diversity_drag=0.25),
            dict(label="Prior lines of systemic therapy", cat="Prior/Concurrent treatment (e.g. line of therapy)",
                 rel="<=", low="{prior_lines}", low_unit="lines", restrictiveness=0.55, diversity_drag=0.45),
            dict(label="Life expectancy", cat="Diagnosis", rel=">=", low="12", low_unit="weeks",
                 restrictiveness=0.30, diversity_drag=0.35),
            dict(label="Adequate organ and marrow function", cat="Lab Values", rel=" =", low="Yes",
                 restrictiveness=0.55, diversity_drag=0.70),
            dict(label="Left ventricular ejection fraction (LVEF)", cat="Procedural Values", rel=">=",
                 low="50", low_unit="%", tp_desc="at", tp_start="screening",
                 restrictiveness=0.40, diversity_drag=0.55),
            dict(label="Availability of archival or fresh tumor tissue", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.50, diversity_drag=0.60),
        ],
        "exclusion": [
            dict(label="Untreated central nervous system metastases", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.45, diversity_drag=0.35),
            dict(label="Prior treatment with an agent of the same mechanistic class",
                 cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =", low="No",
                 restrictiveness=0.50, diversity_drag=0.30),
            dict(label="Unresolved toxicity from prior anticancer therapy", cat="Medical History", rel="<=",
                 low="Grade 1", restrictiveness=0.40, diversity_drag=0.35,
                 notes="Excluding alopecia and stable peripheral neuropathy"),
            dict(label="Active autoimmune disease requiring systemic treatment", cat="Comorbidities",
                 rel=" =", low="No", restrictiveness=0.35, diversity_drag=0.40),
            dict(label="History of interstitial lung disease or non-infectious pneumonitis",
                 cat="Medical History", rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.30),
            dict(label="Radiotherapy", cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =",
                 low="No", tp_rel="<=", tp_val="4", tp_unit="weeks", tp_desc="before", tp_start="first dose",
                 restrictiveness=0.25, diversity_drag=0.25),
        ],
    },
    "Immunology & Inflammation": {
        "inclusion": [
            dict(label="Disease duration", cat="Diagnosis", rel=">=", low="6", low_unit="months",
                 tp_desc="before", tp_start="screening", restrictiveness=0.25, diversity_drag=0.35),
            dict(label="Inadequate response or intolerance to conventional therapy",
                 cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =", low="Yes",
                 restrictiveness=0.45, diversity_drag=0.50),
            dict(label="Tender joint count (68 joints)", cat="Procedural Values", rel=">=", low="6",
                 low_unit="joints", tp_desc="at", tp_start="screening",
                 restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Body surface area (BSA) involvement", cat="Procedural Values", rel=">=", low="10",
                 low_unit="%", tp_desc="at", tp_start="screening", restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Modified Mayo score", cat="Procedural Values", rel=">=", low="5",
                 tp_desc="at", tp_start="screening", restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Stable background therapy", cat="Concomitant Medications", rel=" =", low="Yes",
                 tp_rel=">=", tp_val="8", tp_unit="weeks", tp_desc="before", tp_start="baseline",
                 restrictiveness=0.40, diversity_drag=0.50),
        ],
        "exclusion": [
            dict(label="Prior exposure to biologic therapy", cat="Prior/Concurrent treatment (e.g. line of therapy)",
                 rel="<=", low="{prior_bio}", low_unit="agents", restrictiveness=0.50, diversity_drag=0.40),
            dict(label="Serious or opportunistic infection", cat="Medical History", rel=" =", low="No",
                 tp_rel="<=", tp_val="6", tp_unit="months", tp_desc="before", tp_start="screening",
                 restrictiveness=0.35, diversity_drag=0.55),
            dict(label="History of demyelinating disease", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.20, diversity_drag=0.15),
            dict(label="Live vaccine administration", cat="Concomitant Medications", rel=" =", low="No",
                 tp_rel="<=", tp_val="4", tp_unit="weeks", tp_desc="before", tp_start="baseline",
                 restrictiveness=0.20, diversity_drag=0.25),
        ],
    },
    "Cardiometabolic": {
        "inclusion": [
            dict(label="Glycated hemoglobin (HbA1c)", cat="Lab Values", rel=">=", low="{hba1c_low}",
                 low_unit="%", rel2="<=", high="{hba1c_high}", high_unit="%", tp_desc="at",
                 tp_start="screening", restrictiveness=0.55, diversity_drag=0.55),
            dict(label="Stable background antihyperglycemic therapy", cat="Concomitant Medications",
                 rel=" =", low="Yes", tp_rel=">=", tp_val="12", tp_unit="weeks", tp_desc="before",
                 tp_start="screening", restrictiveness=0.40, diversity_drag=0.55),
            dict(label="New York Heart Association (NYHA) functional class", cat="Diagnosis", rel=">=",
                 low="II", restrictiveness=0.35, diversity_drag=0.35),
            dict(label="N-terminal pro b-type natriuretic peptide (NT-proBNP)", cat="Lab Values", rel=">=",
                 low="300", low_unit="pg/mL", tp_desc="at", tp_start="screening",
                 restrictiveness=0.45, diversity_drag=0.40),
            dict(label="Left ventricular ejection fraction (LVEF)", cat="Procedural Values", rel="<=",
                 low="40", low_unit="%", restrictiveness=0.45, diversity_drag=0.35),
        ],
        "exclusion": [
            dict(label="History of pancreatitis", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.20, diversity_drag=0.25),
            dict(label="Personal or family history of medullary thyroid carcinoma", cat="Medical History",
                 rel=" =", low="No", restrictiveness=0.15, diversity_drag=0.10),
            dict(label="Myocardial infarction, stroke, or hospitalization for unstable angina",
                 cat="Medical History", rel=" =", low="No", tp_rel="<=", tp_val="3", tp_unit="months",
                 tp_desc="before", tp_start="screening", restrictiveness=0.35, diversity_drag=0.60),
            dict(label="Proliferative retinopathy requiring acute treatment", cat="Comorbidities", rel=" =",
                 low="No", restrictiveness=0.25, diversity_drag=0.60),
            dict(label="Bariatric surgery", cat="Medical History", rel=" =", low="No", tp_rel="<=",
                 tp_val="2", tp_unit="years", tp_desc="before", tp_start="screening",
                 restrictiveness=0.20, diversity_drag=0.30),
        ],
    },
    "Neurology": {
        "inclusion": [
            dict(label="Mini-Mental State Examination (MMSE) score", cat="Procedural Values", rel=">=",
                 low="{mmse_low}", rel2="<=", high="{mmse_high}", tp_desc="at", tp_start="screening",
                 restrictiveness=0.55, diversity_drag=0.75,
                 notes="Not adjusted for education or primary language"),
            dict(label="Availability of a study partner", cat="Ability to Consent/Comply", rel=" =",
                 low="Yes", restrictiveness=0.50, diversity_drag=0.70,
                 notes="Study partner must have sufficient contact with the participant"),
            dict(label="Positive amyloid biomarker", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.60, diversity_drag=0.45,
                 notes="By amyloid PET or cerebrospinal fluid assessment"),
            dict(label="Expanded Disability Status Scale (EDSS) score", cat="Procedural Values", rel="<=",
                 low="5.5", tp_desc="at", tp_start="screening", restrictiveness=0.45, diversity_drag=0.35),
            dict(label="Documented relapses", cat="Medical History", rel=">=", low="1", low_unit="events",
                 tp_rel="<=", tp_val="12", tp_unit="months", tp_desc="before", tp_start="screening",
                 restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Seizure frequency", cat="Diagnosis", rel=">=", low="4", low_unit="seizures/month",
                 restrictiveness=0.45, diversity_drag=0.30),
        ],
        "exclusion": [
            dict(label="Other cause of dementia or cognitive impairment", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.35, diversity_drag=0.45),
            dict(label="Contraindication to magnetic resonance imaging", cat="Comorbidities", rel=" =",
                 low="No", restrictiveness=0.25, diversity_drag=0.30),
            dict(label="Evidence of microhemorrhage or superficial siderosis on MRI", cat="Procedural Values",
                 rel="<=", low="4", low_unit="lesions", restrictiveness=0.40, diversity_drag=0.50),
            dict(label="History of major psychiatric disorder", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.35, diversity_drag=0.55),
            dict(label="Anticoagulant therapy", cat="Concomitant Medications", rel=" =", low="No",
                 restrictiveness=0.35, diversity_drag=0.55),
        ],
    },
}

# Procedures every protocol carries, regardless of therapeutic area.
CORE_PROCEDURES = [
    ("Informed consent", "Procedure (Non - Invasive)", 30, "19826-7"),
    ("Inclusion and exclusion criteria", "Procedure (Non - Invasive)", 20, "35514-9"),
    ("Demographics", "Procedure (Non - Invasive)", 10, "72826-1"),
    ("Medical and surgical history", "Procedure (Non - Invasive)", 25, "72185-2"),
    ("Complete physical examination", "Procedure (Non - Invasive)", 30, "22029-3"),
    ("Targeted physical examination", "Procedure (Non - Invasive)", 15, "29545-1"),
    ("Vital signs", "Procedure (Non - Invasive)", 10, "29274-8"),
    ("Height and weight", "Procedure (Non - Invasive)", 5, "8302-2"),
    ("12-lead electrocardiogram (ECG)", "Procedure (Non - Invasive)", 15, "11524-6"),
    ("Hematology panel", "Procedure (Minimally Invasive)", 10, "58410-2"),
    ("Serum chemistry panel", "Procedure (Minimally Invasive)", 10, "24323-8"),
    ("Urinalysis", "Procedure (Non - Invasive)", 10, "24357-6"),
    ("Serum or urine pregnancy test", "Procedure (Minimally Invasive)", 10, "2106-3"),
    ("Prior and concomitant medication review", "Procedure (Non - Invasive)", 15, "10160-0"),
    ("Adverse event assessment", "Procedure (Non - Invasive)", 15, "67498-0"),
    ("Study drug administration", "Procedure (Minimally Invasive)", 45, "80565-1"),
    ("Study drug accountability", "Procedure (Non - Invasive)", 10, "78029-2"),
]

EPOCHS = ["Screening", "Run-in", "Treatment", "Follow-up"]

# --------------------------------------------------------------------------
# Sites. Base demographic mixes are directional, not sourced -- they exist to
# give the corpus internal structure, not to represent real epidemiology.
# --------------------------------------------------------------------------

SITE_TYPES = {
    "Academic Medical Center":      dict(share=0.30, startup_days=(75, 145), enroll_rate=0.55, quality=0.85),
    "Community Hospital":           dict(share=0.24, startup_days=(55, 110), enroll_rate=0.80, quality=0.70),
    "Dedicated Research Site":      dict(share=0.26, startup_days=(35, 80),  enroll_rate=1.45, quality=0.80),
    "Private Practice":             dict(share=0.14, startup_days=(40, 95),  enroll_rate=0.95, quality=0.62),
    "Safety-Net / Public Hospital": dict(share=0.06, startup_days=(90, 175), enroll_rate=0.60, quality=0.65),
}

COUNTRIES = {
    "United States": dict(
        share=0.34,
        race=dict(White=0.62, Black=0.14, Asian=0.07, Indigenous=0.01, Other=0.11, Unknown=0.05),
        ethnicity=dict(hispanic=0.19),
        cities=[("Boston", "MA"), ("New York", "NY"), ("Houston", "TX"), ("Chicago", "IL"),
                ("Los Angeles", "CA"), ("Atlanta", "GA"), ("Philadelphia", "PA"), ("Phoenix", "AZ"),
                ("Miami", "FL"), ("Seattle", "WA"), ("Nashville", "TN"), ("Denver", "CO"),
                ("Cleveland", "OH"), ("St. Louis", "MO"), ("Charlotte", "NC"), ("Detroit", "MI")]),
    "Germany": dict(share=0.09, race=dict(White=0.88, Black=0.02, Asian=0.04, Indigenous=0.0, Other=0.04, Unknown=0.02),
                    ethnicity=dict(hispanic=0.01),
                    cities=[("Berlin", ""), ("Munich", ""), ("Hamburg", ""), ("Cologne", ""), ("Frankfurt", "")]),
    "Spain": dict(share=0.07, race=dict(White=0.86, Black=0.03, Asian=0.02, Indigenous=0.0, Other=0.07, Unknown=0.02),
                  ethnicity=dict(hispanic=0.88),
                  cities=[("Madrid", ""), ("Barcelona", ""), ("Valencia", ""), ("Seville", "")]),
    "Poland": dict(share=0.08, race=dict(White=0.95, Black=0.01, Asian=0.01, Indigenous=0.0, Other=0.02, Unknown=0.01),
                   ethnicity=dict(hispanic=0.0),
                   cities=[("Warsaw", ""), ("Krakow", ""), ("Wroclaw", ""), ("Gdansk", ""), ("Poznan", "")]),
    "United Kingdom": dict(share=0.07, race=dict(White=0.79, Black=0.05, Asian=0.09, Indigenous=0.0, Other=0.05, Unknown=0.02),
                           ethnicity=dict(hispanic=0.01),
                           cities=[("London", ""), ("Manchester", ""), ("Birmingham", ""), ("Leeds", ""), ("Glasgow", "")]),
    "Canada": dict(share=0.06, race=dict(White=0.71, Black=0.04, Asian=0.17, Indigenous=0.03, Other=0.03, Unknown=0.02),
                   ethnicity=dict(hispanic=0.02),
                   cities=[("Toronto", "ON"), ("Montreal", "QC"), ("Vancouver", "BC"), ("Calgary", "AB")]),
    "Japan": dict(share=0.06, race=dict(White=0.01, Black=0.0, Asian=0.97, Indigenous=0.0, Other=0.01, Unknown=0.01),
                  ethnicity=dict(hispanic=0.0),
                  cities=[("Tokyo", ""), ("Osaka", ""), ("Nagoya", ""), ("Fukuoka", "")]),
    "South Korea": dict(share=0.05, race=dict(White=0.01, Black=0.0, Asian=0.97, Indigenous=0.0, Other=0.01, Unknown=0.01),
                        ethnicity=dict(hispanic=0.0),
                        cities=[("Seoul", ""), ("Busan", ""), ("Incheon", "")]),
    "Australia": dict(share=0.05, race=dict(White=0.80, Black=0.01, Asian=0.14, Indigenous=0.02, Other=0.02, Unknown=0.01),
                      ethnicity=dict(hispanic=0.01),
                      cities=[("Sydney", "NSW"), ("Melbourne", "VIC"), ("Brisbane", "QLD"), ("Perth", "WA")]),
    "Brazil": dict(share=0.05, race=dict(White=0.43, Black=0.11, Asian=0.01, Indigenous=0.01, Other=0.42, Unknown=0.02),
                   ethnicity=dict(hispanic=0.95),
                   cities=[("São Paulo", ""), ("Rio de Janeiro", ""), ("Porto Alegre", ""), ("Belo Horizonte", "")]),
    "Hungary": dict(share=0.04, race=dict(White=0.94, Black=0.01, Asian=0.01, Indigenous=0.0, Other=0.03, Unknown=0.01),
                    ethnicity=dict(hispanic=0.0), cities=[("Budapest", ""), ("Debrecen", ""), ("Szeged", "")]),
    "Czechia": dict(share=0.04, race=dict(White=0.95, Black=0.01, Asian=0.01, Indigenous=0.0, Other=0.02, Unknown=0.01),
                    ethnicity=dict(hispanic=0.0), cities=[("Prague", ""), ("Brno", ""), ("Ostrava", "")]),
}

SITE_NAME_PATTERNS = {
    "Academic Medical Center": ["{city} University Medical Center", "{city} University Hospital",
                                "Institute of {spec} at {city}", "{city} Academic Health Sciences Centre"],
    "Community Hospital": ["{city} General Hospital", "{city} Regional Medical Center",
                           "St. {saint} Hospital, {city}", "{city} Community Health Center"],
    "Dedicated Research Site": ["{city} Clinical Research Institute", "{city} Trials Unit",
                                "Accelera Research — {city}", "{city} Investigational Site Network"],
    "Private Practice": ["{city} {spec} Associates", "{city} {spec} Partners",
                         "{spec} Specialists of {city}"],
    "Safety-Net / Public Hospital": ["{city} Public Health System", "{city} County Medical Center",
                                     "{city} Municipal Hospital"],
}

SITE_SPECIALTIES = {
    "Respiratory": "Pulmonary", "Oncology": "Oncology", "Immunology & Inflammation": "Rheumatology",
    "Cardiometabolic": "Cardiometabolic", "Neurology": "Neurology",
}

SAINTS = ["Mary", "Joseph", "Luke", "Michael", "Anne", "Vincent", "Elizabeth", "Francis"]

SPONSOR_STEMS = ["Aldercrest", "Northvane", "Meridian Bio", "Calyx Therapeutics", "Vantiva Pharma",
                 "Solstice Bio", "Harborline", "Cygnet Therapeutics", "Ardent Bio", "Peregrine Pharma",
                 "Lumen Therapeutics", "Kestrel Bio", "Thornfield", "Alder & Vale", "Westmark Bio"]

CRO_NAMES = ["Continental Clinical", "Adaris CRO", "Wexley Research Group", "Pinnacle Trials",
             "Northstar Clinical Services", "In-House"]

MOLECULE_TYPES = ["Small Molecule", "Biologic", "Cell/Gene Therapy", "Vaccine"]

BIOLOGIC_CATEGORIES = [
    "Antibody Drug Conjugates", "Cell-Based Therapy", "Enzymes", "Gene Therapy",
    "Monoclonal Antibody", "Multi-specific Antibody", "Polyclonal Antibodies",
    "Preventative Vaccines", "Recombinant Proteins (non-antibody based)",
    "Synthetic Oligonucleotide/ siRNA", "Synthetic Peptide", "Therapeutic Vaccines",
    "Toxins", "Other", "Unknown",
]

AMENDMENT_SECTIONS = [
    "Section 5.1 Inclusion Criteria", "Section 5.2 Exclusion Criteria",
    "Section 6.1 Study Treatment", "Section 8.1 Schedule of Assessments",
    "Section 3.1 Objectives and Endpoints", "Section 9.2 Statistical Methods",
    "Section 7.3 Prohibited Concomitant Medications", "Section 4.1 Overall Design",
    "Section 10.1 Safety Reporting", "Synopsis",
]


# --------------------------------------------------------------------------
# Extended criterion pools. Appended so per-protocol criteria counts land in
# the same range as the Trial IntelX sample (64-73 criteria per protocol).
# --------------------------------------------------------------------------

UNIVERSAL_INCLUSION += [
    dict(label="Willingness to comply with contraception requirements", cat="Pregnancy/Breastfeeding/Contraception",
         rel=" =", low="Yes", restrictiveness=0.20, diversity_drag=0.15, notes="male participants"),
    dict(label="Negative serum pregnancy test", cat="Pregnancy/Breastfeeding/Contraception", rel=" =",
         low="Negative", tp_desc="at", tp_start="screening", restrictiveness=0.05, diversity_drag=0.0),
    dict(label="Body Weight", cat="Procedural Values", rel=">=", low="40", low_unit="kg",
         restrictiveness=0.20, diversity_drag=0.30),
    dict(label="Systolic Blood Pressure (SBP)", cat="Procedural Values", rel=">=", low="90",
         low_unit="mmHg", rel2="<=", high="160", high_unit="mmHg", tp_desc="at", tp_start="screening",
         restrictiveness=0.35, diversity_drag=0.65, notes="after 5 minutes of rest"),
    dict(label="Diastolic Blood Pressure (DBP)", cat="Procedural Values", rel=">=", low="50",
         low_unit="mmHg", rel2="<=", high="95", high_unit="mmHg", tp_desc="at", tp_start="screening",
         restrictiveness=0.30, diversity_drag=0.60, notes="after 5 minutes of rest"),
    dict(label="Heart Rate (HR)", cat="Procedural Values", rel=">=", low="45", low_unit="bpm",
         rel2="<=", high="100", high_unit="bpm", tp_desc="at", tp_start="screening",
         restrictiveness=0.25, diversity_drag=0.25),
    dict(label="Adequate venous access for protocol-required blood sampling", cat="Procedural Values",
         rel=" =", low="Yes", restrictiveness=0.15, diversity_drag=0.20),
    dict(label="Fluency in a language for which validated patient-reported outcome instruments exist",
         cat="Ability to Consent/Comply", rel=" =", low="Yes", restrictiveness=0.30, diversity_drag=0.85,
         notes="PRO instruments not translated for all site languages"),
    dict(label="Access to reliable transportation for study visits", cat="Ability to Consent/Comply",
         rel=" =", low="Yes", restrictiveness=0.25, diversity_drag=0.80),
    dict(label="Residence within reasonable distance of the study site", cat="Ability to Consent/Comply",
         rel=" =", low="Yes", restrictiveness=0.30, diversity_drag=0.75),
]

UNIVERSAL_EXCLUSION += [
    dict(label="Platelet count", cat="Lab Values", rel=">=", low="100", low_unit="x 10⁹/L",
         restrictiveness=0.35, diversity_drag=0.45),
    dict(label="White blood cell count", cat="Lab Values", rel=">=", low="3.0", low_unit="x 10⁹/L",
         restrictiveness=0.35, diversity_drag=0.70, notes="Benign ethnic neutropenia not accounted for"),
    dict(label="Aspartate aminotransferase (AST)", cat="Lab Values", rel="<=", low="2.5", low_unit="x ULN",
         restrictiveness=0.35, diversity_drag=0.45),
    dict(label="Alkaline phosphatase", cat="Lab Values", rel="<=", low="2.5", low_unit="x ULN",
         restrictiveness=0.25, diversity_drag=0.30),
    dict(label="Serum creatinine", cat="Lab Values", rel="<=", low="1.5", low_unit="x ULN",
         restrictiveness=0.45, diversity_drag=0.75),
    dict(label="International normalised ratio (INR)", cat="Lab Values", rel="<=", low="1.5",
         restrictiveness=0.25, diversity_drag=0.35),
    dict(label="Thyroid stimulating hormone (TSH)", cat="Lab Values", rel=" =", low="normal",
         restrictiveness=0.25, diversity_drag=0.35),
    dict(label="Clinically significant neurological disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.35, diversity_drag=0.40),
    dict(label="Clinically significant psychiatric disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.40, diversity_drag=0.60),
    dict(label="Clinically significant hematologic disease", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.30, diversity_drag=0.55, notes="Includes sickle cell trait in some protocols"),
    dict(label="Clinically significant immunodeficiency", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.30, diversity_drag=0.45),
    dict(label="Uncontrolled hypertension", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.40, diversity_drag=0.75),
    dict(label="Chronic kidney disease stage 4 or higher", cat="Comorbidities", rel=" =", low="No",
         restrictiveness=0.35, diversity_drag=0.70),
    dict(label="History of organ or stem cell transplantation", cat="Medical History", rel=" =", low="No",
         restrictiveness=0.20, diversity_drag=0.25),
    dict(label="History of anaphylaxis to a biologic agent", cat="Allergies/Reactions", rel=" =", low="No",
         restrictiveness=0.15, diversity_drag=0.10),
    dict(label="Known allergy to protocol-required rescue medication", cat="Allergies/Reactions",
         rel=" =", low="No", restrictiveness=0.15, diversity_drag=0.15),
    dict(label="Alcohol consumption above protocol-defined threshold", cat="Substance Abuse", rel="<=",
         low="14", low_unit="units per week", restrictiveness=0.30, diversity_drag=0.35),
    dict(label="Positive urine drug screen", cat="Substance Abuse", rel=" =", low="Negative",
         tp_desc="at", tp_start="screening", restrictiveness=0.35, diversity_drag=0.60),
    dict(label="Cannabis use", cat="Substance Abuse", rel=" =", low="No", tp_rel="<=", tp_val="30",
         tp_unit="days", tp_desc="before", tp_start="screening", restrictiveness=0.30, diversity_drag=0.45),
    dict(label="Prior randomization in this study", cat="Prior/Concurrent participation in a trial",
         rel=" =", low="No", restrictiveness=0.10, diversity_drag=0.05),
    dict(label="Employee or family member of the sponsor or investigational site",
         cat="Ability to Consent/Comply", rel=" =", low="No", restrictiveness=0.05, diversity_drag=0.05),
    dict(label="Blood donation or significant blood loss", cat="Medical History", rel=" =", low="No",
         tp_rel="<=", tp_val="8", tp_unit="weeks", tp_desc="before", tp_start="screening",
         restrictiveness=0.15, diversity_drag=0.15),
    dict(label="Planned major surgery during the study period", cat="Medical History", rel=" =", low="No",
         restrictiveness=0.20, diversity_drag=0.25),
    dict(label="Vulnerable population status", cat="Ability to Consent/Comply", rel=" =", low="No",
         restrictiveness=0.20, diversity_drag=0.55,
         notes="Includes institutionalized individuals and those under legal guardianship"),
    dict(label="Inability to attend all protocol-required visits", cat="Ability to Consent/Comply",
         rel=" =", low="No", restrictiveness=0.35, diversity_drag=0.80),
    dict(label="Night shift or rotating shift work", cat="Ability to Consent/Comply", rel=" =", low="No",
         restrictiveness=0.30, diversity_drag=0.70,
         notes="Interferes with protocol-required fasting and morning assessments"),
    dict(label="Receipt of a live attenuated vaccine", cat="Concomitant Medications", rel=" =", low="No",
         tp_rel="<=", tp_val="4", tp_unit="weeks", tp_desc="before", tp_start="baseline",
         restrictiveness=0.20, diversity_drag=0.20),
    dict(label="Use of strong CYP3A4 inhibitors or inducers", cat="Concomitant Medications", rel=" =",
         low="No", tp_rel="<=", tp_val="14", tp_unit="days", tp_desc="before", tp_start="baseline",
         restrictiveness=0.35, diversity_drag=0.40),
    dict(label="Use of herbal supplements or traditional medicines", cat="Concomitant Medications",
         rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.65),
    dict(label="Chronic use of non-steroidal anti-inflammatory drugs", cat="Concomitant Medications",
         rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.40),
]

_TA_EXTRA = {
    "Respiratory": {
        "inclusion": [
            dict(label="Forced Vital Capacity (FVC)", cat="Diagnosis", rel=">=", low="50",
                 low_unit="% of predicted normal value", restrictiveness=0.45, diversity_drag=0.35),
            dict(label="Peak expiratory flow variability", cat="Procedural Values", rel=">=", low="20",
                 low_unit="%", restrictiveness=0.40, diversity_drag=0.25),
            dict(label="Demonstrated correct inhaler technique", cat="Ability to Consent/Comply", rel=" =",
                 low="Yes", restrictiveness=0.30, diversity_drag=0.50),
            dict(label="Ability to perform reproducible spirometry", cat="Ability to Consent/Comply",
                 rel=" =", low="Yes", restrictiveness=0.35, diversity_drag=0.45),
            dict(label="Diffusing capacity (DLCO)", cat="Procedural Values", rel=">=", low="30",
                 low_unit="% predicted", restrictiveness=0.45, diversity_drag=0.40),
        ],
        "exclusion": [
            dict(label="Long-term oxygen therapy", cat="Concomitant Medications", rel=" =", low="No",
                 restrictiveness=0.35, diversity_drag=0.55),
            dict(label="History of lung volume reduction surgery or transplantation", cat="Medical History",
                 rel=" =", low="No", restrictiveness=0.20, diversity_drag=0.20),
            dict(label="Alpha-1 antitrypsin deficiency", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.15, diversity_drag=0.15),
            dict(label="Pulmonary hypertension", cat="Comorbidities", rel=" =", low="No",
                 restrictiveness=0.30, diversity_drag=0.40),
            dict(label="Occupational exposure to respiratory irritants", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.30, diversity_drag=0.75),
            dict(label="Obstructive sleep apnea requiring CPAP", cat="Comorbidities", rel=" =", low="No",
                 restrictiveness=0.25, diversity_drag=0.55),
        ],
    },
    "Oncology": {
        "inclusion": [
            dict(label="Documented disease progression on prior therapy",
                 cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =", low="Yes",
                 restrictiveness=0.40, diversity_drag=0.30),
            dict(label="Biomarker-positive tumor status", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.65, diversity_drag=0.55,
                 notes="Requires central laboratory confirmation"),
            dict(label="Recovery from prior therapy toxicity", cat="Medical History", rel="<=",
                 low="Grade 1", restrictiveness=0.35, diversity_drag=0.35),
            dict(label="Absolute lymphocyte count", cat="Lab Values", rel=">=", low="0.5",
                 low_unit="x 10⁹/L", restrictiveness=0.35, diversity_drag=0.50),
            dict(label="Creatinine clearance", cat="Lab Values", rel=">=", low="60",
                 low_unit="mL/min", restrictiveness=0.50, diversity_drag=0.75),
            dict(label="Willingness to undergo on-treatment tumor biopsy", cat="Ability to Consent/Comply",
                 rel=" =", low="Yes", restrictiveness=0.55, diversity_drag=0.65),
        ],
        "exclusion": [
            dict(label="Active infection requiring systemic therapy", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.30, diversity_drag=0.45),
            dict(label="Leptomeningeal disease", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.25, diversity_drag=0.20),
            dict(label="Prior allogeneic stem cell transplant", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.20, diversity_drag=0.20),
            dict(label="Clinically significant ascites or pleural effusion requiring drainage",
                 cat="Comorbidities", rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.35),
            dict(label="History of severe immune-related adverse events", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.25, diversity_drag=0.20),
            dict(label="Second primary malignancy requiring active treatment", cat="Comorbidities",
                 rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.35),
        ],
    },
    "Immunology & Inflammation": {
        "inclusion": [
            dict(label="C-reactive protein (CRP)", cat="Lab Values", rel=">=", low="6", low_unit="mg/L",
                 restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Swollen joint count (66 joints)", cat="Procedural Values", rel=">=", low="6",
                 low_unit="joints", restrictiveness=0.45, diversity_drag=0.30),
            dict(label="Investigator Global Assessment (IGA) score", cat="Procedural Values", rel=">=",
                 low="3", restrictiveness=0.40, diversity_drag=0.30),
            dict(label="Documented endoscopic disease activity", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.55, diversity_drag=0.55,
                 notes="Requires central reading of endoscopy performed within screening window"),
            dict(label="Willingness to undergo protocol-required endoscopy",
                 cat="Ability to Consent/Comply", rel=" =", low="Yes",
                 restrictiveness=0.50, diversity_drag=0.60),
        ],
        "exclusion": [
            dict(label="History of malignancy other than adequately treated skin cancer",
                 cat="Medical History", rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.30),
            dict(label="Positive interferon-gamma release assay without completed prophylaxis",
                 cat="Medical History", rel=" =", low="No", restrictiveness=0.35, diversity_drag=0.75),
            dict(label="Chronic hepatitis B or C infection", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.30, diversity_drag=0.70),
            dict(label="Recent intra-articular corticosteroid injection", cat="Concomitant Medications",
                 rel=" =", low="No", tp_rel="<=", tp_val="4", tp_unit="weeks", tp_desc="before",
                 tp_start="baseline", restrictiveness=0.25, diversity_drag=0.30),
            dict(label="Fibromyalgia or other chronic pain condition confounding assessment",
                 cat="Comorbidities", rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.45),
            dict(label="Prior inadequate response to more than two biologic agents",
                 cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =", low="No",
                 restrictiveness=0.50, diversity_drag=0.40),
        ],
    },
    "Cardiometabolic": {
        "inclusion": [
            dict(label="Body Mass Index (BMI) for obesity indication", cat="Procedural Values", rel=">=",
                 low="27", low_unit="kg/m²", restrictiveness=0.35, diversity_drag=0.30),
            dict(label="Fasting C-peptide", cat="Lab Values", rel=">=", low="0.6", low_unit="ng/mL",
                 restrictiveness=0.35, diversity_drag=0.40),
            dict(label="Documented history of cardiovascular disease", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.40, diversity_drag=0.35),
            dict(label="Stable body weight", cat="Procedural Values", rel="<=", low="5", low_unit="% change",
                 tp_rel="<=", tp_val="12", tp_unit="weeks", tp_desc="before", tp_start="screening",
                 restrictiveness=0.40, diversity_drag=0.45),
            dict(label="Willingness to maintain diet and exercise counselling",
                 cat="Ability to Consent/Comply", rel=" =", low="Yes",
                 restrictiveness=0.30, diversity_drag=0.60),
        ],
        "exclusion": [
            dict(label="Type 1 diabetes mellitus", cat="Comorbidities", rel=" =", low="No",
                 restrictiveness=0.20, diversity_drag=0.15),
            dict(label="History of diabetic ketoacidosis", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.25, diversity_drag=0.50),
            dict(label="Severe hypoglycemia requiring assistance", cat="Medical History", rel=" =",
                 low="No", tp_rel="<=", tp_val="6", tp_unit="months", tp_desc="before",
                 tp_start="screening", restrictiveness=0.30, diversity_drag=0.55),
            dict(label="Heart transplantation or ventricular assist device", cat="Medical History",
                 rel=" =", low="No", restrictiveness=0.15, diversity_drag=0.20),
            dict(label="Atrial fibrillation with uncontrolled ventricular rate", cat="Comorbidities",
                 rel=" =", low="No", restrictiveness=0.30, diversity_drag=0.45),
            dict(label="Uncontrolled dyslipidemia", cat="Comorbidities", rel=" =", low="No",
                 restrictiveness=0.30, diversity_drag=0.50),
        ],
    },
    "Neurology": {
        "inclusion": [
            dict(label="Clinical Dementia Rating (CDR) global score", cat="Procedural Values", rel=">=",
                 low="0.5", rel2="<=", high="1.0", restrictiveness=0.55, diversity_drag=0.60),
            dict(label="Stable dose of symptomatic medication", cat="Concomitant Medications", rel=" =",
                 low="Yes", tp_rel=">=", tp_val="12", tp_unit="weeks", tp_desc="before",
                 tp_start="baseline", restrictiveness=0.40, diversity_drag=0.50),
            dict(label="Confirmed diagnosis by McDonald criteria", cat="Diagnosis", rel=" =", low="Yes",
                 restrictiveness=0.35, diversity_drag=0.35),
            dict(label="Ability to complete cognitive assessments in the site's language",
                 cat="Ability to Consent/Comply", rel=" =", low="Yes",
                 restrictiveness=0.40, diversity_drag=0.90,
                 notes="Cognitive batteries not validated across all languages or education levels"),
            dict(label="Minimum years of formal education", cat="Ability to Consent/Comply", rel=">=",
                 low="6", low_unit="years", restrictiveness=0.35, diversity_drag=0.90,
                 notes="Applied for cognitive test norming"),
        ],
        "exclusion": [
            dict(label="History of stroke or transient ischemic attack", cat="Medical History", rel=" =",
                 low="No", restrictiveness=0.35, diversity_drag=0.65),
            dict(label="Significant white matter disease on MRI", cat="Procedural Values", rel=" =",
                 low="No", restrictiveness=0.35, diversity_drag=0.60),
            dict(label="Vitamin B12 deficiency or untreated hypothyroidism", cat="Lab Values", rel=" =",
                 low="No", restrictiveness=0.25, diversity_drag=0.45),
            dict(label="Active suicidal ideation on C-SSRS", cat="Medical History", rel=" =", low="No",
                 restrictiveness=0.25, diversity_drag=0.40),
            dict(label="Progressive or secondary progressive disease course", cat="Diagnosis", rel=" =",
                 low="No", restrictiveness=0.35, diversity_drag=0.30),
            dict(label="Prior treatment with an anti-amyloid monoclonal antibody",
                 cat="Prior/Concurrent treatment (e.g. line of therapy)", rel=" =", low="No",
                 restrictiveness=0.30, diversity_drag=0.25),
        ],
    },
}

for _ta, _extra in _TA_EXTRA.items():
    TA_CRITERIA[_ta]["inclusion"] += _extra["inclusion"]
    TA_CRITERIA[_ta]["exclusion"] += _extra["exclusion"]

# Additional shared procedures, so SOA schedules vary more between protocols.
CORE_PROCEDURES += [
    ("Coagulation panel", "Procedure (Minimally Invasive)", 10, "34714-6"),
    ("Serology panel (HIV, HBV, HCV)", "Procedure (Minimally Invasive)", 15, "75622-1"),
    ("Urine drug and alcohol screen", "Procedure (Non - Invasive)", 15, "3426-3"),
    ("Columbia-Suicide Severity Rating Scale (C-SSRS)", "Procedure (Non - Invasive)", 15, "93373-9"),
    ("Patient-reported outcome questionnaire", "Procedure (Non - Invasive)", 20, "72133-2"),
    ("EQ-5D-5L health status questionnaire", "Procedure (Non - Invasive)", 10, "89571-4"),
    ("Healthcare resource utilization questionnaire", "Procedure (Non - Invasive)", 15, "86645-1"),
    ("Pharmacokinetic blood sampling", "Procedure (Minimally Invasive)", 15, "33747-3"),
    ("Anti-drug antibody sampling", "Procedure (Minimally Invasive)", 10, "33748-1"),
    ("Biomarker blood sampling", "Procedure (Minimally Invasive)", 15, "33747-3"),
    ("Pharmacogenomic sampling (optional)", "Procedure (Minimally Invasive)", 15, "55232-3"),
    ("Randomization", "Procedure (Non - Invasive)", 10, "78026-8"),
    ("Study drug dispensing and training", "Procedure (Non - Invasive)", 25, "80565-1"),
    ("Diary card review", "Procedure (Non - Invasive)", 10, "68503-6"),
    ("Follow-up telephone contact", "Procedure (Non - Invasive)", 15, "68520-0"),
    ("Concomitant therapy reconciliation", "Procedure (Non - Invasive)", 15, "10160-0"),
]
